app = "pedro-portfolio"
primary_region = "gru"

[env]
  PORT = "8080"
  RAILS_ENV = "production"

[processes]
  app = "bundle exec puma -C config/puma.rb"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]


[[vm]]
  memory = "1gb"
  cpus = 1

[deploy]
  release_command = "bin/rails db:migrate"